---
title: "test graphs"
output: html_notebook
---


```{r}
pacman::p_load(tidyverse, readxl, janitor, scales, glue, ggrepel)
```

```{r}
data_raw <- read_excel("data_in/examples for graphs.xlsx", sheet = "data") %>% 
  clean_names()

targets_raw <- read_excel("data_in/examples for graphs.xlsx", sheet = "targets") %>% 
  clean_names()

data_raw
targets_raw
```

```{r}
#actual
data <- data_raw 

#target - shows latest and the target
target_data <- data %>% 
  select(sd_number, year, value) %>% 
  bind_rows(targets_raw) %>% 
  group_by(sd_number) %>% 
  arrange(desc(year)) %>% 
  slice(1:2) %>% 
  arrange(year)

target_data
```




```{r}
#sd 3
sd3 <- data %>% 
  filter(sd_number == 3) %>% 
  mutate(value = round(value*100, 1)) 

sd3t <- target_data %>% 
  filter(sd_number == 3) %>% 
  mutate(value = round(value*100, 1))

#ggplot(sd3, aes(factor(year), value)) +
#  geom_col(fill = "#E55048") + 
#  labs(title = "Feeling safe when walking during the night", 
#       subtitle = "Healthy and safe",
#       caption = "The percentage of residents who either select 'safe' or 'very safe' when walking alone in their local area during the night.", 
#       x = NULL, y = "Percentage") + 
#  theme_minimal()  +
#  geom_text(aes(label = sprintf("%0.1f", value), y = 5), col = "white", fontface = "bold") +
#  annotate("segment", x = 0.5, xend = 2.5, y = 80, yend = 80, colour = "#E55048") + 
#  annotate("text", x = 2.25, y = 85, label = "2040 target: 80%") +
#  annotate("rect", xmin = 1.5, xmax = 2.5, ymin = 50, ymax = 75, alpha = 0.2) + 
#  annotate("text", x = 2, y = 62.5, label = "Gap of 34.4 percentage points")
```

```{r}
ggplot(sd3, aes(year, value), col = "#E55048") + #actual data
  geom_line(size = 1.5, col = "#E55048") + #actual data
  geom_line(data = sd3t, aes(year, value), linetype = "dashed", col = "#E55048") + #to target
  geom_point(data = sd3, aes(year, value), size = 5, col = "#E55048") +  #actual data
  geom_point(data = sd3t, aes(year, value), size = 5, col = "#E55048") + #to target
  geom_text_repel(data = sd3, aes(year, value, label = value), fontface = "bold", vjust = 0, nudge_y = 2.5) + #actual data
  geom_text_repel(data = sd3t %>% filter(year == 2040), aes(year, value, label = value), fontface = "bold", vjust = 0, nudge_y = 2.5) +  #to target
  theme_minimal()  +
  labs(title = "Feeling safe when walking during the night", 
       subtitle = "Healthy and safe",
       caption = "The percentage of residents who either select 'safe' or 'very safe' when walking alone in their local area during the night.", 
       x = "Year", y = "Percentage") +
  annotate("text", x = 2036, y = 60, label = "Gap of 34.4 percentage points\n to the 2040 target") +
  ylim (0, 85) # height of chart 
ggsave("data_out/feeling_safe.svg")
```





```{r}
#sd 6
sd6 <- data %>% 
  filter(sd_number == 6) %>% 
  mutate(value = round(value*100, 1)) 

sd6t <- target_data %>% 
  filter(sd_number == 6) %>% 
  mutate(value = round(value*100, 1))


#
#ggplot(sd6, aes(factor(year), value)) +
#  geom_col(fill = "#31788F") + 
#  labs(title = "Kindergarten enrolment",
#       subtitle = "Learn and work",
#       caption = "Number of first year children enrolled in kindergarten divided by the number of 3 year old children (70%)\n and 4 year old children (30%) based on the previous year's estimated #resident population", 
#       x = NULL, y = "Percentage") + 
#  theme_minimal()  +
#  geom_text(aes(label = sprintf("%0.1f", value), y = 5), col = "white", fontface = "bold") +
#  annotate("segment", x = 0.5, xend = 2.5, y = 96.2, yend = 96.2, colour = "#31788F") + 
#  annotate("text", x = 2.25, y = 100, label = "2040 target: 96.2%") +
#  annotate("rect", xmin = 1.5, xmax = 2.5, ymin = 92, ymax = 96, alpha = 0.2) + 
#  annotate("text", x = 2, y = 94, label = "Gap of 4.6 percentage points")
```

```{r}
ggplot(sd6, aes(year, value), col = "#31788F") + #actual data
  geom_line(size = 1.5, col = "#31788F") + #actual data
  geom_line(data = sd6t, aes(year, value), linetype = "dashed", col = "#31788F") + #to target
  geom_point(data = sd6, aes(year, value), size = 5, col = "#31788F") +  #actual data
  geom_point(data = sd6t, aes(year, value), size = 5, col = "#31788F") + #to target
  geom_text_repel(data = sd6, aes(year, value, label = value), fontface = "bold", vjust = 0, nudge_y = 2.5) + #actual data
  geom_text_repel(data = sd6t %>% filter(year == 2040), aes(year, value, label = value), fontface = "bold", vjust = 0, nudge_y = 2.5) +  #to target
  theme_minimal()  +
  labs(title = "Kindergarten enrolment",
       subtitle = "Learn and work",
       caption = "Number of first year children enrolled in kindergarten divided by the number of 3 year old children (70%)\n and 4 year old children (30%) based on the previous year's estimated resident population", 
       x = "Year", y = "Percentage") +
  annotate("text", x = 2036, y = 93, label = "Gap of 4.6 percentage points\n to the 2040 target") +
  ylim (85, 100) # height of chart
ggsave("data_out/kindergerten_enrolment.svg")
```


```{r}
#sd 10
sd10 <- data %>% 
  filter(sd_number == 10) %>% 
  mutate(value = round(value*100, 1)) 

sd10t <- target_data %>% 
  filter(sd_number == 10) %>% 
  mutate(value = round(value*100, 1))

#ggplot(sd10, aes(factor(year), value)) +
#  geom_col(fill = "#6A4479") + 
#  labs(title = "Residents who travel to work using active or sustainable transport methods",
#       subtitle = "Sustainable and active transport",
#       caption = "Proportion who travel to work by walking, cycling or by public transport", 
#       x = NULL, y = "Percentage") + 
#  theme_minimal()  +
#  geom_text(aes(label = sprintf("%0.1f", value), y = 5), col = "white", fontface = "bold") +
#  annotate("segment", x = 0.5, xend = 3.5, y = 50.1, yend = 50.1, colour = "#6A4479") + 
#  annotate("text", x = 3.25, y = 52, label = "2040 target: 50.1%") +
#  annotate("rect", xmin = 2.5, xmax = 3.5, ymin = 25, ymax = 47.5, alpha = 0.2) + 
#  annotate("text", x = 3, y = 35, label = "Gap of 26.4 \npercentage points")
```

```{r}
ggplot(sd10, aes(year, value), col = "#6A4479") + #actual data
  geom_line(size = 1.5, col = "#6A4479") + #actual data
  geom_line(data = sd10t, aes(year, value), linetype = "dashed", col = "#6A4479") + #to target
  geom_point(data = sd10, aes(year, value), size = 5, col = "#6A4479") +  #actual data
  geom_point(data = sd10t, aes(year, value), size = 5, col = "#6A4479") + #to target
  geom_text_repel(data = sd10, aes(year, value, label = value), fontface = "bold", vjust = 0, nudge_y = 2.5) + #actual data
  geom_text_repel(data = sd10t %>% filter(year == 2040), aes(year, value, label = value), fontface = "bold", vjust = 0, nudge_y = 2.5) +  #to target
  theme_minimal()  +
  labs(title = "Residents who travel to work using active or sustainable transport methods",
       subtitle = "Sustainable and active transport",
       caption = "Proportion who travel to work by walking, cycling or by public transport", 
       x = "Year", y = "Percentage") +
  annotate("text", x = 2036, y = 35, label = "Gap of 26.4 percentage points\n to the 2040 target") +
  ylim (0, 60) # height of chart
ggsave("data_out/sustainable_transport_methods.svg")
```


```{r}
#sd 15
sd15 <- data %>% 
  filter(sd_number == 15) %>% 
  mutate(value = round(value*100, 1)) 

sd15t <- target_data %>% 
  filter(sd_number == 15) %>% 
  mutate(value = round(value*100, 1))

#ggplot(sd15, aes(factor(year), value)) +
#  geom_col(fill = "#4EA546") + 
#  labs(title = "Kerbside waste collected and diverted from landfill",
#       subtitle = "Waste",
#       caption = "Percentage of garbage, recyclables and green organics collected \nfrom kerbside bins that is diverted from landfill", 
#       x = NULL, y = "Percentage") + 
#  theme_minimal()  +
#  geom_text(aes(label = sprintf("%0.1f", value), y = 5), col = "white", fontface = "bold") +
#  annotate("segment", x = 0.5, xend = 4.5, y = 90, yend = 90, colour = "#4EA546") + 
#  annotate("text", x = 4.25, y = 94, label = "2040 target: 90%") +
#  annotate("rect", xmin = 3.5, xmax = 4.5, ymin = 50, ymax = 85, alpha = 0.2) + 
#  annotate("text", x = 4, y = 67.5, label = "Gap of 38.3 \npercentage points")
```

```{r}
ggplot(sd15, aes(year, value), col = "#4EA546") + #actual data
  geom_line(size = 1.5, col = "#4EA546") + #actual data
  geom_line(data = sd15t, aes(year, value), linetype = "dashed", col = "#4EA546") + #to target
  geom_point(data = sd15, aes(year, value), size = 5, col = "#4EA546") +  #actual data
  geom_point(data = sd15t, aes(year, value), size = 5, col = "#4EA546") + #to target
  geom_text_repel(data = sd15, aes(year, value, label = value), fontface = "bold", vjust = 0, nudge_y = 2.5) + #actual data
  geom_text_repel(data = sd15t %>% filter(year == 2040), aes(year, value, label = value), fontface = "bold", vjust = 0, nudge_y = 2.5) +  #to target
  theme_minimal()  +
  labs(title = "Kerbside waste collected and diverted from landfill",
       subtitle = "Waste",
       caption = "Percentage of garbage, recyclables and green organics collected \nfrom kerbside bins that is diverted from landfill", 
       x = "Year", y = "Percentage") +
  annotate("text", x = 2036, y = 65, label = "Gap of 38.3 percentage points\n to the 2040 target") +
  ylim (0, 100) # height of chart
ggsave("data_out/kerbside_waste.svg")
```


```{r}
#sd 18
sd18 <- data %>% 
  filter(sd_number == 18) %>% 
  mutate(value = round(value*100, 1)) 

sd18t <- target_data %>% 
  filter(sd_number == 18) %>% 
  mutate(value = round(value*100, 1))

#ggplot(sd18, aes(factor(year), value)) +
#  geom_col(fill = "#E3A51E") + 
#  labs(title = "Council facilities that are disability accessible",
#       subtitle = "Quality design",
#       caption = "Percentage of Council facilities that are disability accessible", 
#       x = NULL, y = "Percentage") + 
#  theme_minimal()  +
#  geom_text(aes(label = sprintf("%0.1f", value), y = 5), col = "white", fontface = "bold") +
#  annotate("segment", x = 0.5, xend = 2.5, y = 100, yend = 100, colour = "#E3A51E") + 
#  annotate("text", x = 2.25, y = 105, label = "2040 target: 100%") +
#  annotate("rect", xmin = 1.5, xmax = 2.5, ymin = 85, ymax = 95, alpha = 0.2) + 
#  annotate("text", x = 2, y = 90, label = "Gap of 20 percentage points")
```

```{r}
ggplot(sd18, aes(year, value), col = "#E3A51E") + #actual data
  geom_line(size = 1.5, col = "#E3A51E") + #actual data
  geom_line(data = sd18t, aes(year, value), linetype = "dashed", col = "#E3A51E") + #to target
  geom_point(data = sd18, aes(year, value), size = 5, col = "#E3A51E") +  #actual data
  geom_point(data = sd18t, aes(year, value), size = 5, col = "#E3A51E") + #to target
  geom_text_repel(data = sd18, aes(year, value, label = value), fontface = "bold", vjust = 0, nudge_y = 2.5) + #actual data
  geom_text_repel(data = sd18t %>% filter(year == 2040), aes(year, value, label = value), fontface = "bold", vjust = 0, nudge_y = 2.5) +  #to target
  theme_minimal()  +
  labs(title = "Council facilities that are disability accessible",
       subtitle = "Quality design",
       caption = "Percentage of Council facilities that are disability accessible", 
       x = "Year", y = "Percentage") +
  annotate("text", x = 2036, y = 90, label = "Gap of 20 percentage points\n to the 2040 target") +
  ylim (60, 100) # height of chart
ggsave("data_out/faciliites_accessible.svg")
```

